#!/bin/bash

. ${TOOL_DIR}/functions

function brief()
{
    echo "--test-lely-core=[no|<path>]"
}

function help()
{
    brief
    cat <<EOF
    If this option is given with a <path> to the compiled lely-core tests tree, the full tree will be imported
    on the target under /data/lely-core from which you can execute the lely-core test suite using:

    cd /data/lely-core
    ./run_testsuites.sh

    NOTE: You must compile the lely-core tests tree of the desired target before building
    the vm image.

    The default is no.
EOF
}

function validate() {

	if [ ${OPT_TEST_LELY_CORE} != no ]; then
		if [ ! -d ${OPT_TEST_LELY_CORE} ]; then
			echo "Invalid lely core source tree '${OPT_TEST_LELY_CORE}'"
			exit 1;
		fi
	else
		exit 0;
	fi
}

function configure()
{
	rm -f output/option_files/*.opt_test_lely_core
	if [ ${OPT_TEST_LELY_CORE} != no ]; then
		if [ ${OPT_VERBOSE} == yes ]; then
			echo "Building lely-core file list from ${OPT_TEST_LELY_CORE}"
		fi

		for f in $(find ${OPT_TEST_LELY_CORE} -type f); do
			echo "[perms=0755] lely-core/${f#${OPT_TEST_LELY_CORE}/}=${f}" >> output/option_files/data_files.opt_test_lely_core
		done;

		case ${OPT_ARCH} in
		x86*)
			LELY_CORE_TEST_PREFIX="nto-${OPT_ARCH}-o";
			;;
		*aarch64*)
			LELY_CORE_TEST_PREFIX="nto-aarch64-le";
			;;
		esac

		# export lely-core options"
		echo "LELY_CORE_TEST_PREFIX=${LELY_CORE_TEST_PREFIX}" >> output/option_files/ifs_env.opt_test_lely_core

	fi

	exit 0
}

case "$1" in
	brief)
		brief;;
	help)
		help;;
	validate)
		validate;;
	configure)
		configure;;
	default)
		echo no;;
esac
